import React, { createContext, useContext, useState, useEffect } from 'react';

// Define available languages
const LANGUAGES = {
  ENGLISH: 'en',
  CHINESE: 'zh',
};

// Export separately for compatibility with hot reloading
export { LANGUAGES };

// Define translations
const translations = {
  [LANGUAGES.ENGLISH]: {
    // Header & Navigation
    searchPlaceholder: 'Search courses...',
    resourcesHub: 'ResourcesHub',
    shareConnect: 'Share & Connect',
    recentSearches: 'Recent Searches',
    profile: 'Profile',
    bookmarks: 'Bookmarks',
    signOut: 'Sign Out',
    myAccount: 'My Account',
    hide: 'Hide',
    show: 'Show',
    english: 'English',
    chinese: 'Chinese',
    learningHowToLearn: 'Learning How to Learn',
    learning: 'Learning',
    language: 'Language',
    viewProfile: 'View Profile',
    overview: 'Overview',
    connectWithOthers: 'Connect & Chat',
    notes: 'Notes',
    chat: 'Chat',
    
    // Home/Hero Section
    discoverLearningPath: 'Discover Your Learning Path',
    personalizedRecommendations: 'Personalized recommendations to help you advance your skills and career.',
    learnGrowSucceed: 'Learn.Grow.Succeed',
    
    // Course Listing
    sortBy: 'Sort by:',
    recommended: 'Recommended',
    highestRated: 'Highest Rated',
    mostPopular: 'Most Popular',
    newest: 'Newest',
    recommendedCourses: 'Recommended Courses',
    searchResults: 'Search Results: "{query}"',
    filtersApplied: 'Filters applied',
    showingCoursesMatchingFilters: 'Showing courses matching your filters',
    filtersReset: 'Filters reset',
    showingAllCourses: 'Showing all courses',
    
    // Filters & Categories
    category: 'Category',
    subCategory: 'Sub-Category',
    courseType: 'Course Type',
    filterBy: 'Filter by',
    ratingPrefix: '',  // Empty in English
    ratingSuffix: '+ Rating',
    applyFilters: 'Apply Filters',
    resetFilters: 'Reset Filters',
    skills: 'Skills',
    
    // Pagination
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    
    // Toast Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    
    // AI Assistant related translations
    chatWithAI: 'Chat with AI',
    sendMessage: 'Send Message',
    typeYourMessage: 'Type your message...',
    newChat: 'New Chat',
    history: 'History',
    apiSettings: 'API Settings',
    selectModel: 'Select Model',
    temperature: 'Temperature',
    maxTokens: 'Max Tokens',
    aiProvider: 'Provider',
    openAI: 'OpenAI',
    anthropic: 'Anthropic',
    openRouter: 'OpenRouter',
    apiKey: 'API Key',
    baseUrl: 'Base URL (Optional)',
    customModelId: 'Custom Model ID',
    save: 'Save',
    cancel: 'Cancel',
    configure: 'Configure',
    openAIModels: 'OpenAI Models',
    anthropicModels: 'Anthropic Models',
    openRouterModels: 'OpenRouter Models',
    settings: 'Settings',
    assistant: 'Assistant',
    saveConversation: 'Save Conversation',
    deleteConversation: 'Delete Conversation',
    conversations: 'Conversations',
    noConversations: 'No conversations yet',
    startChatting: 'Start chatting now!',
    conversationTitle: 'Conversation Title',
    renameConversation: 'Rename Conversation',
    loadingModels: 'Loading models...',
    
    // User Profile
    followers: 'Followers',
    following: 'Following',
    posts: 'Posts',
    likes: 'Likes',
    comments: 'Comments',
    follow: 'Follow',
    unfollow: 'Unfollow',
    editProfile: 'Edit Profile',
    
    // Errors
    errorOccurred: 'An error occurred',
    pleaseEnterMessage: 'Please enter a message',
    pleaseEnterAPIKey: 'Please enter an API Key',
    pleaseSelectProvider: 'Please select an AI provider',
    pleaseSelectModel: 'Please select a model',
    
    // Filter messages
    noCategoriesAvailable: 'No categories available',
    noSubCategoriesAvailable: 'No subcategories available',
    noCourseTypesAvailable: 'No course types available',
    
    // Bookmark messages
    authRequired: 'Authentication required',
    signInToBookmark: 'Please sign in to bookmark courses',
    loginAgainToBookmark: 'Please login again to bookmark courses',
    bookmarkRemoved: 'Bookmark removed',
    bookmarkRemovedDescription: '{title} has been removed from your bookmarks',
    bookmarkAdded: 'Bookmark added',
    bookmarkAddedDescription: '{title} has been added to your bookmarks',
    alreadyBookmarked: 'Already bookmarked',
    alreadyBookmarkedDescription: '{title} is already in your bookmarks',
    bookmarkUpdateError: 'Failed to update bookmark. Please try again.',
    addBookmark: 'Add to bookmarks',
    removeBookmark: 'Remove from bookmarks',
    
    // Course Detail Page
    courseNotFound: 'Course Not Found',
    courseNotFoundMessage: 'We couldn\'t find the course you\'re looking for. It may have been removed or you might have followed an invalid link.',
    backToCourses: 'Back to Courses',
    aboutThisCourse: 'About This Course',
    instructors: 'Instructors',
    duration: 'Duration',
    enrolled: 'Enrolled',
    students: 'students',
    subtitlesAvailableIn: 'Subtitles Available In',
    skillsYoullGain: 'Skills You\'ll Gain',
    enrollInThisCourse: 'Enroll in This Course',
    courseProvider: 'Provider',
    type: 'Type',
    goToCourse: 'Go to Course',
    bookmarked: 'Bookmarked',
    bookmark: 'Bookmark',
    share: 'Share',
    studentsEnrolled: 'students enrolled',
    beFirstToEnroll: 'Be the first to enroll!',
    alreadyRemoved: 'Already removed',
    courseAlreadyRemoved: 'This course was already removed from your bookmarks',
    operationFailed: 'Operation Failed',
    bookmarkUpdateFailed: 'Failed to update bookmark. Please check your connection and try again.',
    courseAddedToBookmarks: '{title} has been added to your bookmarks',
    courseAlreadyInBookmarks: '{title} is already in your bookmarks',
    linkCopied: 'Link copied',
    courseLinkCopied: 'Course link copied to clipboard',
    
    // ===== Learning How To Learn Page Translations =====
    // Overview Tab
    masterArtOfLearning: 'Master the Art of Learning',
    welcomeToLearningJourney: 'Welcome to your personal learning transformation journey. Explore powerful techniques and strategies that will revolutionize how you acquire and retain knowledge.',
    ourMissionIs: 'Our mission is to equip you with the skills to learn anything effectively and efficiently. Explore our learning techniques and center to develop abilities that will benefit you for life.',
    whyLearnHowToLearn: 'Why Learn How to Learn?',
    learningHowToLearnIsValuable: 'Learning how to learn is perhaps the most valuable skill you can acquire. It forms the foundation for:',
    acceleratedSkillAcquisition: 'Accelerated Skill Acquisition',
    masterNewSubjects: 'Master new subjects in significantly less time',
    betterRetention: 'Enhanced Retention',
    rememberLonger: 'Remember what you learn for much longer periods',
    deeperUnderstanding: 'Deeper Understanding',
    comprehendComplex: 'Comprehend complex topics more thoroughly',
    lifelongAdaptability: 'Lifelong Adaptability',
    stayRelevant: 'Stay relevant in a rapidly evolving world',
    whatYoullDiscover: 'What You\'ll Discover',
    ourPlatformOffers: 'Our platform offers focused approaches to improving your learning capabilities:',
    learningTechniques: 'Learning Techniques',
    masterProvenMethods: 'Master scientifically-proven methods to enhance learning efficiency and memory retention',
    learningCenter: 'Learning Center',
    accessStructuredGuides: 'Access structured guides and exercises to practice effective learning strategies',
    cognitiveInsights: 'Cognitive Insights',
    understandHowBrain: 'Understand how your brain processes and retains information for optimal learning',
    practicalExercises: 'Practical Exercises',
    applyTechniques: 'Apply techniques through guided exercises designed to strengthen learning skills',
    readyToTransform: 'Ready to Transform Your Learning Approach?',
    startYourJourney: 'Begin your journey and explore our rich collection of learning techniques that will help you learn faster, remember more, and achieve better results in any subject.',
    discoverLearningTechniques: 'Discover Learning Techniques',
    
    // Techniques Tab
    learningTechniquesHeading: 'Learning Techniques',
    discoverResearchBacked: 'Discover research-backed methods to enhance your learning capacity, improve memory retention, and make the learning process more enjoyable and effective.',
    pomodoroTechnique: 'The Pomodoro Technique',
    pomodoroDescription: 'Work in focused 25-minute intervals followed by short 5-minute breaks. After completing four cycles, take a longer break of about 15-30 minutes.',
    improvesFocusProductivity: 'Improves focus and productivity',
    spacedRepetition: 'Spaced Repetition',
    spacedRepetitionDescription: 'Review information at progressively increasing intervals over time instead of cramming all at once. This approach strengthens long-term memory pathways.',
    bestForLongTerm: 'Best for long-term retention',
    activeRecall: 'Active Recall',
    activeRecallDescription: 'Actively stimulate memory by testing yourself on what you\'ve learned rather than passively reviewing material. This helps strengthen neural connections.',
    strengthensKnowledge: 'Strengthens knowledge retention',
    feynmanTechnique: 'The Feynman Technique',
    feynmanDescription: 'Explain concepts in simple language as if teaching someone else. This helps identify gaps in your understanding and reinforces what you know.',
    deepensConceptual: 'Deepens conceptual understanding',
    combineTechniques: 'Combine these techniques for maximum learning effectiveness!',
    
    // Learning Center Tab
    welcomeToLearningCenter: 'Welcome to the Learning Center',
    comprehensiveHub: 'Your comprehensive hub for educational resources, from university courses to proven learning methodologies and productivity tools.',
    discoverEliteCourses: 'Discover elite courses from top universities, explore evidence-based learning techniques, and find specialized tools to enhance your learning journey.',
    universityCourses: 'University Courses',
    accessPremiumCourses: 'Access premium courses from prestigious universities like MIT, Stanford, and Harvard. Filter by institution, department, or subject area.',
    learningMethodsTitle: 'Learning Methods',
    discoverScienceBacked: 'Explore science-backed learning techniques such as spaced repetition, active recall, the Feynman technique, and more to optimize your study habits.',
    effectivenessRatings: 'Effectiveness Ratings',
    eachMethodIncludes: 'Each method includes research-supported effectiveness ratings and difficulty levels to help you choose the right techniques.',
    learningTools: 'Learning Tools',
    findPerfectTools: 'Find the perfect tools to support your learning journey, from flashcard applications and note-taking software to research tools and productivity enhancers.',
    filterByCategory: 'Filter by category, price, or user ratings',
    personalizedRecommendationsTitle: 'Personalized Recommendations',
    receiveTailored: 'Receive tailored course and resource suggestions based on your interests, learning style, and previous activity to accelerate your educational journey.',
    smartFiltering: 'Smart Filtering',
    advancedSearch: 'Advanced search and filtering options help you find exactly what you need when you need it.',
    readyToEnhance: 'Ready to Enhance Your Learning?',
    accessOurComprehensive: 'Access our comprehensive database of courses, methods, and tools to elevate your educational journey to new heights.',
    exploreLearningCenter: 'Explore Learning Center',
    
    // Share & Connect Tab
    shareConnectWithLearners: 'Share & Connect with Fellow Learners',
    joinVibrantCommunity: 'Join a vibrant community of lifelong learners to share insights, techniques, and resources that help each other grow.',
    exchangeIdeas: 'Exchange ideas, discover new learning approaches, find inspiration, and connect with others who are passionate about continuous learning and self-improvement.',
    shareYourInsights: 'Share Your Insights',
    postYourThoughts: 'Post your thoughts, discoveries, and "aha!" moments about learning. Help others benefit from your experiences and insights.',
    likePosts: 'Like posts that resonate with you',
    applyMethods: 'Apply Effective Methods',
    discoverAndShare: 'Discover and share effective learning techniques. Apply methods that work for others and track your progress as you master them.',
    applicableLearningMethods: 'Applicable Learning Methods',
    seeAMethod: 'See a method that works? Apply it directly to your learning practice and track your progress over time.',
    learningResources: 'Learning Resources',
    shareValuableBooks: 'Share valuable books, articles, videos, courses, and tools that have aided your learning journey. Discover new resources recommended by the community.',
    accessDirectLinks: 'Access direct links to valuable resources',
    engageDiscuss: 'Engage & Discuss',
    commentOnPosts: 'Comment on posts, start discussions, and engage in meaningful conversations about learning strategies, challenges, and breakthroughs.',
    communityDrivenLearning: 'Community-Driven Learning',
    learnFaster: 'Learn faster by leveraging the collective wisdom and experiences of your learning peers.',
    readyToJoin: 'Ready to Join the Conversation?',
    connectWithFellow: 'Connect with fellow learners, share your insights, and discover new techniques that can transform your learning journey.',
    exploreShareConnect: 'Explore Share & Connect',
    
    // Chat Tab
    connectThroughChat: 'Connect Through Chat',
    engageInRealTime: 'Engage in real-time conversations with learning peers to exchange ideas, ask questions, and deepen your understanding of learning concepts.',
    ourChatPlatform: 'Our chat platform facilitates one-on-one discussions and group conversations, creating a supportive environment for collaborative learning.',
    directMessages: 'Direct Messages',
    connectOneOnOne: 'Connect one-on-one with peers who share your learning interests. Build meaningful relationships and exchange personalized advice on specific learning challenges.',
    connectWithFollowers: 'Connect with Followers',
    easilyFind: 'Easily find and message your mutual followers to cultivate a supportive network of learning connections.',
    groupChats: 'Group Chats',
    createAndJoin: 'Create and join topic-focused group chats to discuss specific learning subjects, techniques, or courses with multiple participants simultaneously.',
    studyGroupsMadeEasy: 'Study Groups Made Easy',
    formVirtualStudy: 'Form virtual study groups, coordinate learning activities, and share resources in real-time with your learning circle.',
    chatPlatformFeatures: 'Chat Platform Features',
    realTimeMessaging: 'Real-Time Messaging',
    instantMessage: 'Instant message delivery with typing indicators and read receipts for seamless conversations.',
    learningFocused: 'Learning-Focused',
    purposeBuilt: 'Purpose-built for educational discussions with features that enhance collaborative learning.',
    privacyControls: 'Privacy Controls',
    connectOnlyWith: 'Connect only with mutual followers to ensure conversations remain within your trusted network.',
    seamlessExperience: 'Seamless Experience',
    modernIntuitive: 'Modern, intuitive interface designed for distraction-free learning communication.',
    readyToStartChatting: 'Ready to Start Chatting?',
    joinConversations: 'Join conversations with learners who share your passion for growth and discovery. Exchange ideas, ask questions, and build your learning network.',
    openChat: 'Open Chat',
    
    // Calendar & Deadlines
    calendarTitle: 'My Deadlines',
    calendarUpcoming: 'Upcoming Deadlines',
    calendarAdd: 'Add',
    calendarAddNew: 'Add New Deadline',
    calendarClearFilter: 'Clear filter',
    calendarNoEvents: 'No upcoming deadlines',
    calendarAddFirst: 'Add your first deadline',
    calendarLoading: 'Loading deadlines...',
    calendarFailed: 'Failed to load deadlines',
    calendarCompleted: 'Completed',
    calendarMarkCompleted: 'Mark as completed',
    calendarDeadline: 'Deadline',
    calendarNotes: 'Notes',
    calendarNotesPlaceholder: 'Add any details you need to remember',
    calendarNotesEmpty: 'No notes added',
    calendarRelatedCourse: 'Related Course',
    calendarCourseUnavailable: 'Course information unavailable',
    calendarDueDate: 'Due date & time',
    calendarWhatsDue: "What's due?",
    calendarTitlePlaceholder: 'Assignment name, exam, etc.',
    calendarCancel: 'Cancel',
    calendarAdding: 'Adding...',
    calendarAddDeadline: 'Add Deadline',
    calendarDeadlineAdded: 'Deadline added',
    calendarDeadlineAddedDesc: 'Your deadline has been added to your calendar',
    calendarDeadlineRemoved: 'Removed',
    calendarDeadlineRemovedDesc: 'Deadline has been removed',
    calendarDeadlineCompleted: 'Completed!',
    calendarDeadlineCompletedDesc: 'Task marked as complete',
    calendarDeadlineError: 'Error',
    calendarDeadlineErrorDesc: 'Failed to create deadline',
    calendarBackToList: 'Back to list',
    calendarDelete: 'Delete',
    calendarDueToday: 'Due today',
    calendarDueTomorrow: 'Due tomorrow',
    calendarOverdue: 'OVERDUE',
    calendarDaysRemaining: '{count} days remaining',
    calendarHoursRemaining: '{count}h remaining',
  },
  [LANGUAGES.CHINESE]: {
    // Header & Navigation
    searchPlaceholder: '搜索课程...',
    resourcesHub: '资源中心',
    shareConnect: '分享与连接',
    recentSearches: '最近搜索',
    profile: '个人资料',
    bookmarks: '收藏',
    signOut: '退出登录',
    myAccount: '我的账户',
    hide: '隐藏',
    show: '显示',
    english: '英语',
    chinese: '中文',
    learningHowToLearn: '学习如何学习',
    learning: '学习',
    language: '语言',
    viewProfile: '查看个人资料',
    overview: '概览',
    connectWithOthers: '连接与聊天',
    notes: '笔记',
    chat: '聊天',
    
    // Home/Hero Section
    discoverLearningPath: '探索您的学习之路',
    personalizedRecommendations: '个性化推荐，帮助您提升技能和推进事业发展。',
    learnGrowSucceed: '学习.成长.成功',
    
    // Course Listing
    sortBy: '排序方式：',
    recommended: '推荐',
    highestRated: '评分最高',
    mostPopular: '最受欢迎',
    newest: '最新',
    recommendedCourses: '推荐课程',
    searchResults: '搜索结果："{query}"',
    filtersApplied: '已应用筛选条件',
    showingCoursesMatchingFilters: '显示符合筛选条件的课程',
    filtersReset: '筛选条件已重置',
    showingAllCourses: '显示所有课程',
    
    // Filters & Categories
    category: '类别',
    subCategory: '子类别',
    courseType: '课程类型',
    filterBy: '筛选条件',
    ratingPrefix: '',  // Empty in Chinese
    ratingSuffix: '+ 评分',
    applyFilters: '应用筛选条件',
    resetFilters: '重置筛选条件',
    skills: '技能',
    
    // Pagination
    previous: '上一页',
    next: '下一页',
    page: '页',
    of: '/',
    
    // Toast Messages
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '信息',
    
    // AI Assistant related translations
    chatWithAI: '与AI聊天',
    sendMessage: '发送消息',
    typeYourMessage: '输入您的消息...',
    newChat: '新对话',
    history: '历史记录',
    apiSettings: 'API设置',
    selectModel: '选择模型',
    temperature: '温度',
    maxTokens: '最大令牌数',
    aiProvider: '提供商',
    openAI: 'OpenAI',
    anthropic: 'Anthropic',
    openRouter: 'OpenRouter',
    apiKey: 'API密钥',
    baseUrl: '基础URL（可选）',
    customModelId: '自定义模型ID',
    save: '保存',
    cancel: '取消',
    configure: '配置',
    openAIModels: 'OpenAI模型',
    anthropicModels: 'Anthropic模型',
    openRouterModels: 'OpenRouter模型',
    settings: '设置',
    assistant: '助手',
    saveConversation: '保存对话',
    deleteConversation: '删除对话',
    conversations: '对话列表',
    noConversations: '暂无对话',
    startChatting: '立即开始聊天！',
    conversationTitle: '对话标题',
    renameConversation: '重命名对话',
    loadingModels: '加载模型中...',
    
    // User Profile
    followers: '关注者',
    following: '关注中',
    posts: '帖子',
    likes: '点赞',
    comments: '评论',
    follow: '关注',
    unfollow: '取消关注',
    editProfile: '编辑资料',
    
    // Errors
    errorOccurred: '发生错误',
    pleaseEnterMessage: '请输入消息',
    pleaseEnterAPIKey: '请输入API密钥',
    pleaseSelectProvider: '请选择AI提供商',
    pleaseSelectModel: '请选择模型',
    
    // Filter messages
    noCategoriesAvailable: '没有可用的类别',
    noSubCategoriesAvailable: '没有可用的子类别',
    noCourseTypesAvailable: '没有可用的课程类型',
    
    // Bookmark messages
    authRequired: '需要认证',
    signInToBookmark: '请登录以收藏课程',
    loginAgainToBookmark: '请重新登录以收藏课程',
    bookmarkRemoved: '已移除收藏',
    bookmarkRemovedDescription: '{title} 已从您的收藏中移除',
    bookmarkAdded: '已添加收藏',
    bookmarkAddedDescription: '{title} 已添加到您的收藏',
    alreadyBookmarked: '已经收藏',
    alreadyBookmarkedDescription: '{title} 已在您的收藏中',
    bookmarkUpdateError: '更新收藏失败。请重试。',
    addBookmark: '添加到收藏',
    removeBookmark: '从收藏中移除',
    
    // Course Detail Page
    courseNotFound: '未找到课程',
    courseNotFoundMessage: '我们找不到您要查找的课程。它可能已被删除或您可能访问了无效链接。',
    backToCourses: '返回课程',
    aboutThisCourse: '关于此课程',
    instructors: '讲师',
    duration: '时长',
    enrolled: '已报名',
    students: '学生',
    subtitlesAvailableIn: '可用字幕语言',
    skillsYoullGain: '您将获得的技能',
    enrollInThisCourse: '报名参加此课程',
    courseProvider: '提供者',
    type: '类型',
    goToCourse: '前往课程',
    bookmarked: '已收藏',
    bookmark: '收藏',
    share: '分享',
    studentsEnrolled: '学生已报名',
    beFirstToEnroll: '成为首位报名者！',
    alreadyRemoved: '已移除',
    courseAlreadyRemoved: '此课程已从您的收藏中移除',
    operationFailed: '操作失败',
    bookmarkUpdateFailed: '更新收藏失败。请检查您的连接并重试。',
    courseAddedToBookmarks: '{title} 已添加到您的收藏',
    courseAlreadyInBookmarks: '{title} 已在您的收藏中',
    linkCopied: '链接已复制',
    courseLinkCopied: '课程链接已复制到剪贴板',
    
    // ===== Learning How To Learn Page Translations =====
    // Overview Tab
    masterArtOfLearning: '掌握学习的艺术',
    welcomeToLearningJourney: '欢迎开始您的个人学习转变之旅。探索强大的技巧和策略，彻底改变您获取和保留知识的方式。',
    ourMissionIs: '我们的使命是让您掌握有效高效学习任何知识的技能。探索我们的学习技巧和中心，培养终身受益的技能。',
    whyLearnHowToLearn: '为什么要学习如何学习？',
    learningHowToLearnIsValuable: '学习如何学习可能是您能获得的最有价值的技能。这是以下几方面的基础：',
    acceleratedSkillAcquisition: '加速技能获取',
    masterNewSubjects: '在更短的时间内掌握新主题',
    betterRetention: '更好的记忆力',
    rememberLonger: '更长时间记住所学内容',
    deeperUnderstanding: '更深入的理解',
    comprehendComplex: '更全面地理解复杂主题',
    lifelongAdaptability: '终身适应能力',
    stayRelevant: '在快速变化的世界中保持相关性',
    whatYoullDiscover: '您将探索的内容',
    ourPlatformOffers: '我们的平台提供了改善您学习能力的专注方法：',
    learningTechniques: '学习技巧',
    masterProvenMethods: '掌握经过验证的方法以提高学习效率和记忆力',
    learningCenter: '学习中心',
    accessStructuredGuides: '获取结构化指南和练习，以实践有效的学习策略',
    cognitiveInsights: '认知见解',
    understandHowBrain: '了解您的大脑如何处理和保留信息',
    practicalExercises: '实用练习',
    applyTechniques: '通过旨在增强学习技能的指导练习应用技巧',
    readyToTransform: '准备好改变您的学习方式了吗？',
    startYourJourney: '开始您的旅程，探索我们丰富的学习技巧集合，帮助您学习更快、记忆更多，并在任何学科中取得更好的成果。',
    discoverLearningTechniques: '探索学习技巧',
    
    // Techniques Tab
    learningTechniquesHeading: '学习技巧',
    discoverResearchBacked: '探索有研究支持的方法，提升您的学习能力，改善记忆力，使学习过程更加愉快和有效。',
    pomodoroTechnique: '番茄工作法',
    pomodoroDescription: '以25分钟为一个专注工作周期，然后短暂休息5分钟。完成四个周期后，休息较长时间，约15-30分钟。',
    improvesFocusProductivity: '提高专注力和生产力',
    spacedRepetition: '间隔重复',
    spacedRepetitionDescription: '随着时间的推移以递增的间隔复习信息，而不是一次性集中学习。这种方法增强了长期记忆。',
    bestForLongTerm: '最适合长期记忆',
    activeRecall: '主动回忆',
    activeRecallDescription: '通过测试自己所学的内容来积极刺激记忆，而不是被动地复习材料。这有助于加强神经连接。',
    strengthensKnowledge: '增强知识保留',
    feynmanTechnique: '费曼技巧',
    feynmanDescription: '用简单的语言解释概念，就像在教别人一样。这有助于识别你理解中的空白并强化你所知道的内容。',
    deepensConceptual: '深化概念理解',
    combineTechniques: '结合这些技巧以获得最佳学习效果！',
    
    // Learning Center Tab
    welcomeToLearningCenter: '欢迎来到学习中心',
    comprehensiveHub: '您全面的教育资源中心，从大学课程到经过验证的学习方法和生产力工具。',
    discoverEliteCourses: '发现顶尖大学的精英课程，探索循证学习技术，找到专业工具来增强您的学习之旅。',
    universityCourses: '大学课程',
    accessPremiumCourses: '获取麻省理工学院、斯坦福大学和哈佛大学等著名大学的优质课程。按机构、院系或学科领域筛选。',
    learningMethodsTitle: '学习方法',
    discoverScienceBacked: '探索科学支持的学习技术，如间隔重复、主动回忆、费曼技巧等，以优化您的学习习惯。',
    effectivenessRatings: '效果评级',
    eachMethodIncludes: '每种方法都包括研究支持的有效性评级和难度级别，帮助您选择合适的技术。',
    learningTools: '学习工具',
    findPerfectTools: '找到完美的工具来支持您的学习之旅，从flashcard应用和笔记软件到研究工具和提高生产力的工具。',
    filterByCategory: '按类别、价格或用户评分筛选',
    personalizedRecommendationsTitle: '个性化推荐',
    receiveTailored: '根据您的兴趣、学习风格和以前的活动接收量身定制的课程和资源建议，加速您的教育之旅。',
    smartFiltering: '智能筛选',
    advancedSearch: '高级搜索和筛选选项帮助您在需要时找到确切所需的内容。',
    readyToEnhance: '准备好提升您的学习了吗？',
    accessOurComprehensive: '访问我们全面的课程、方法和工具数据库，将您的教育之旅提升到新的水平。',
    exploreLearningCenter: '探索学习中心',
    
    // Share & Connect Tab
    shareConnectWithLearners: '与学习者分享和连接',
    joinVibrantCommunity: '加入充满活力的终身学习者社区，分享见解、技巧和资源，互相帮助成长。',
    exchangeIdeas: '交流想法，发现新的学习方法，寻找灵感，并与其他热衷于持续学习和自我提升的人联系。',
    shareYourInsights: '分享您的见解',
    postYourThoughts: '发布您关于学习的想法、发现和"啊哈！"时刻。帮助他人从您的经验和见解中受益。',
    likePosts: '为与您产生共鸣的帖子点赞',
    applyMethods: '应用有效的方法',
    discoverAndShare: '发现并分享有效的学习技巧。应用对他人有效的方法，并在掌握它们时跟踪您的进度。',
    applicableLearningMethods: '适用的学习方法',
    seeAMethod: '看到一个有效的方法？将其直接应用于您的学习实践并随时间跟踪您的进度。',
    learningResources: '学习资源',
    shareValuableBooks: '分享对您的学习之旅有帮助的宝贵书籍、文章、视频、课程和工具。发现社区推荐的新资源。',
    accessDirectLinks: '访问宝贵资源的直接链接',
    engageDiscuss: '参与讨论',
    commentOnPosts: '评论帖子，开始讨论，并就学习策略、挑战和突破进行有意义的对话。',
    communityDrivenLearning: '社区驱动的学习',
    learnFaster: '通过利用学习伙伴的集体智慧和经验学习更快。',
    readyToJoin: '准备好加入对话了吗？',
    connectWithFellow: '与学习伙伴联系，分享您的见解，发现可以改变您学习之旅的新技术。',
    exploreShareConnect: '探索分享与连接',
    
    // Chat Tab
    connectThroughChat: '通过聊天连接',
    engageInRealTime: '与学习伙伴进行实时对话，交流想法，提问，并加深您对学习概念的理解。',
    ourChatPlatform: '我们的聊天平台促进一对一讨论和群组对话，为协作学习创造支持性环境。',
    directMessages: '私信',
    connectOneOnOne: '与分享您学习兴趣的同伴一对一连接。建立有意义的关系，并就特定学习挑战交换个性化建议。',
    connectWithFollowers: '与关注者连接',
    easilyFind: '轻松找到并向您的互相关注的人发送信息，培养支持性学习网络。',
    groupChats: '群聊',
    createAndJoin: '创建和加入主题聚焦的群聊，与多个参与者同时讨论特定学习主题、技巧或课程。',
    studyGroupsMadeEasy: '轻松组建学习小组',
    formVirtualStudy: '形成虚拟学习小组，协调学习活动，并与您的学习圈实时共享资源。',
    chatPlatformFeatures: '聊天平台特点',
    realTimeMessaging: '实时消息',
    instantMessage: '即时消息传递，带有输入指示器和已读回执，实现无缝对话。',
    learningFocused: '专注学习',
    purposeBuilt: '专为教育讨论而构建，具有增强协作学习的功能。',
    privacyControls: '隐私控制',
    connectOnlyWith: '仅与互相关注的人连接，确保对话保持在您信任的网络内。',
    seamlessExperience: '无缝体验',
    modernIntuitive: '现代、直观的界面，专为无干扰的学习交流而设计。',
    readyToStartChatting: '准备好开始聊天了吗？',
    joinConversations: '加入与分享您对成长和发现热情的学习者的对话。交流想法，提问，并建立您的学习网络。',
    openChat: '打开聊天',
    
    // Calendar & Deadlines
    calendarTitle: '我的截止事项',
    calendarUpcoming: '即将到来的截止事项',
    calendarAdd: '添加',
    calendarAddNew: '添加新截止事项',
    calendarClearFilter: '清除筛选',
    calendarNoEvents: '暂无截止事项',
    calendarAddFirst: '添加您的第一个截止事项',
    calendarLoading: '加载截止事项中...',
    calendarFailed: '加载截止事项失败',
    calendarCompleted: '已完成',
    calendarMarkCompleted: '标记为已完成',
    calendarDeadline: '截止时间',
    calendarNotes: '备注',
    calendarNotesPlaceholder: '添加您需要记住的细节',
    calendarNotesEmpty: '暂无备注',
    calendarRelatedCourse: '相关课程',
    calendarCourseUnavailable: '课程信息不可用',
    calendarDueDate: '截止日期和时间',
    calendarWhatsDue: '事项名称',
    calendarTitlePlaceholder: '作业名称、考试等',
    calendarCancel: '取消',
    calendarAdding: '添加中...',
    calendarAddDeadline: '添加截止事项',
    calendarDeadlineAdded: '已添加',
    calendarDeadlineAddedDesc: '您的截止事项已添加到日历',
    calendarDeadlineRemoved: '已移除',
    calendarDeadlineRemovedDesc: '截止事项已被移除',
    calendarDeadlineCompleted: '已完成！',
    calendarDeadlineCompletedDesc: '任务已标记为完成',
    calendarDeadlineError: '错误',
    calendarDeadlineErrorDesc: '创建截止事项失败',
    calendarBackToList: '返回列表',
    calendarDelete: '删除',
    calendarDueToday: '今天截止',
    calendarDueTomorrow: '明天截止',
    calendarOverdue: '已逾期',
    calendarDaysRemaining: '剩余{count}天',
    calendarHoursRemaining: '剩余{count}小时',
  },
};

// Create the context
const LanguageContext = createContext();

// Create a provider component
export function LanguageProvider({ children }) {
  // Get the language from localStorage or default to English
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || LANGUAGES.ENGLISH;
  });

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
    // Update document language attribute
    document.documentElement.lang = language;
  }, [language]);

  // Translation function
  const t = (key) => {
    return translations[language][key] || key;
  };

  // Context value
  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

// Custom hook to use the language context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}